-- MySQL Script generated by MySQL Workbench
-- Mon May 29 04:48:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
CREATE DATABASE IF NOT EXISTS role;

USE role;

-- -----------------------------------------------------
-- Table `enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enderecos` (
  `cep` INT NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `país` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cep`)
);

-- -----------------------------------------------------
-- Table `eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos` (
  `id_evento` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `data_inicio` TIMESTAMP NULL,
  `data_fim` TIMESTAMP NULL,
  `enderecos_cep` INT NOT NULL,
  `complemento_endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`id_evento`, `enderecos_cep`),
  CONSTRAINT `fk_eventos_enderecos1` FOREIGN KEY (`enderecos_cep`) REFERENCES `enderecos` (`cep`) 
);

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_usuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `foto_de_perfil_url` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`)
);

-- -----------------------------------------------------
-- Table `convidados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `convidados` (
  `eventos_id_evento` INT NOT NULL,
  `usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`eventos_id_evento`, `usuarios_id_usuario`),
  CONSTRAINT `fk_eventos_has_usuarios_eventos` FOREIGN KEY (`eventos_id_evento`) REFERENCES `eventos` (`id_evento`) ,
  CONSTRAINT `fk_eventos_has_usuarios_usuarios1` FOREIGN KEY (`usuarios_id_usuario`) REFERENCES `usuarios` (`id_usuario`) 
);

-- -----------------------------------------------------
-- Table `insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos` (
  `id_insumo` INT NOT NULL,
  `tipo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_insumo`)
);

-- -----------------------------------------------------
-- Table `transacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transacoes` (
  `id_transacao` INT NOT NULL,
  `valor` DECIMAL(10, 2) NOT NULL,
  `data` TIMESTAMP NOT NULL,
  `usuarios_id_usuario` INT NOT NULL,
  `insumos_id_insumo` INT NOT NULL,
  PRIMARY KEY (
    `id_transacao`,
    `usuarios_id_usuario`,
    `insumos_id_insumo`
  ),
  CONSTRAINT `fk_transacoes_usuarios1` FOREIGN KEY (`usuarios_id_usuario`) REFERENCES `usuarios` (`id_usuario`) ,
  CONSTRAINT `fk_transacoes_insumos1` FOREIGN KEY (`insumos_id_insumo`) REFERENCES `insumos` (`id_insumo`) 
);

-- -----------------------------------------------------
-- Table `eventos_has_insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos_has_insumos` (
  `eventos_id_evento` INT NOT NULL,
  `insumos_id_insumo` INT NOT NULL,
  PRIMARY KEY (`eventos_id_evento`, `insumos_id_insumo`),
  CONSTRAINT `fk_eventos_has_insumos_eventos1` FOREIGN KEY (`eventos_id_evento`) REFERENCES `eventos` (`id_evento`) ,
  CONSTRAINT `fk_eventos_has_insumos_insumos1` FOREIGN KEY (`insumos_id_insumo`) REFERENCES `insumos` (`id_insumo`) 
);
